//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ESF.Database.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESF_DataStoreEntities : DbContext
    {
        public ESF_DataStoreEntities()
            : base("name=ESF_DataStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SourceFile> SourceFiles { get; set; }
        public virtual DbSet<SupplementaryData> SupplementaryDatas { get; set; }
        public virtual DbSet<SupplementaryDataUnitCost> SupplementaryDataUnitCosts { get; set; }
        public virtual DbSet<ValidationError> ValidationErrors { get; set; }
        public virtual DbSet<VersionInfo> VersionInfoes { get; set; }
    }
}
