


GO
ALTER ROLE [DataProcessor] ADD MEMBER [ESF_RW_User];
GO
ALTER ROLE [DataViewer] ADD MEMBER [ESF_RW_User];
GO
ALTER ROLE [DataViewer] ADD MEMBER [ESF_RO_User];
GO
ALTER ROLE [DataViewer] ADD MEMBER [User_DSCI];
GO